apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: managedclusters.containerservices.azure.com
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.resourceGroup
    name: ResourceGroup
    type: string
  - JSONPath: .spec.location
    name: Location
    type: string
  - JSONPath: .spec.kubernetesVersion
    name: Version
    type: string
  - JSONPath: .status.provisioningState
    name: State
    type: string
  group: containerservices.azure.com
  names:
    kind: ManagedCluster
    plural: managedclusters
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            addons:
              type: object
            dnsPrefix:
              type: string
            identity:
              properties:
                clientID:
                  type: string
                secretName:
                  type: string
              type: object
            kubernetesVersion:
              type: string
            linux:
              properties:
                adminUsername:
                  type: string
                authorizedKeys:
                  items:
                    type: string
                  type: array
              type: object
            location:
              type: string
            network:
              properties:
                dnsServiceIP:
                  type: string
                dockerBridgeCidr:
                  type: string
                plugin:
                  type: string
                podCidr:
                  type: string
                policy:
                  type: string
                serviceCidr:
                  type: string
              type: object
            nodePools:
              items:
                properties:
                  name:
                    type: string
                  nodeSpec:
                    properties:
                      maxPods:
                        format: int32
                        type: integer
                      osDiskSizeGB:
                        format: int32
                        type: integer
                      vmSize:
                        type: string
                      vnetSubnetID:
                        type: string
                    type: object
                  size:
                    format: int32
                    type: integer
                type: object
              type: array
            rbac:
              type: boolean
            resourceGroup:
              type: string
            subscriptionID:
              type: string
            tags:
              type: object
          type: object
        status:
          properties:
            fqdn:
              type: string
            nodeResourceGroup:
              type: string
            provisioningState:
              type: string
            resourceID:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
